#include "mem/parser/NodeTypes.hpp"
namespace mem { namespace parser {
const char* node_names[] = {"Unknown" 


   , "And"
   , "Binary"
   , "BinaryAddition"
   , "BinarySubstraction"
   , "BinaryMultiplication"
   , "BinaryDivision"
   , "Block"
   , "Call"
   , "Class"
   , "Class"
   , "Divide"
   , "Dot"
   , "ExpressionList"
   , "Field"
   , "File"
   , "FinalID"
   , "Function"
   , "Function"
   , "Parameters"
   , "Parameter"
   , "Group"
   , "ID"
   , "If"
   , "IfElse"
   , "IfElif"
   , "IfElifElse"
   , "Interface"
   , "LeftUnary"
   , "LiteralString"
   , "LiteralInt"
   , "LiteralNumber"
   , "Minus"
   , "Multiply"
   , "Namespace"
   , "New"
   , "Number"
   , "Power"
   , "Object"
   , "Or"
   , "Patch"
   , "PlaceHolder"
   , "Plus"
   , "Primitive"
   , "Return"
   , "Root"
   , "Self"
   , "Text"
   , "Variable"
   , "VariableDeclaration"
   , "Use"
   , "While"
};
}}

