#ifndef MEM_PARSER_NODE_TYPES
#define MEM_PARSER_NODE_TYPES

#define MEM_NODE_BINARY 1
#define MEM_NODE_BINARY_ADD 2
#define MEM_NODE_BINARY_SUB 3
#define MEM_NODE_BINARY_MUL 4
#define MEM_NODE_BINARY_DIV 5
#define MEM_NODE_BLOCK 6
#define MEM_NODE_CALL 7
#define MEM_NODE_CLASS 8
#define MEM_NODE_CLASS_DECLARATION 9
#define MEM_NODE_DOT 10
#define MEM_NODE_EXPR_LIST 11
#define MEM_NODE_FIELD 12
#define MEM_NODE_FILE 13
#define MEM_NODE_FINAL_ID 14
#define MEM_NODE_FUNCTION 15
#define MEM_NODE_FUNCTION_DECLARATION 16
#define MEM_NODE_FUNCTION_PARAMETERS 17
#define MEM_NODE_FUNCTION_PARAMETER 18
#define MEM_NODE_GROUP 19
#define MEM_NODE_ID 20
#define MEM_NODE_IF 21
#define MEM_NODE_IF_ELSE 22
#define MEM_NODE_IF_ELIF 23
#define MEM_NODE_IF_ELIF_ELSE 24
#define MEM_NODE_INTERFACE_DECLARATION 25
#define MEM_NODE_LEFT_UNARY 26
#define MEM_NODE_LITERAL_STRING 27
#define MEM_NODE_LITERAL_INT 28
#define MEM_NODE_NAMESPACE 29
#define MEM_NODE_OBJECT_DECLARATION 30
#define MEM_NODE_PATCH_DECLARATION 31
#define MEM_NODE_PRIMITIVE 32
#define MEM_NODE_RETURN 33
#define MEM_NODE_ROOT 34
#define MEM_NODE_SELF 35
#define MEM_NODE_TEXT 36
#define MEM_NODE_VARIABLE 37
#define MEM_NODE_VARIABLE_DECLARATION 38
#define MEM_NODE_USE 39
#define MEM_NODE_WHILE 40

namespace mem { namespace parser {
extern const char* node_names[];
}}

#endif
